### PR TITLE
Updated ctrtool Linux x86_64,added binary of MergeExHeader and 3dstoo…

### PR DESCRIPTION
**Pull request by mariogamer2**
…l for x86_64

### CODE REVIEW

**Comment by d0k3** [comment]
Is this tested?

**Comment by mariogamer2** [comment]
Will test now.

**Comment by lhallam** [comment]
Yeah, this works for me at least, and the files which have been added are the right architecture:

```
 Universal-Inject-Generator git:(master) file tools/3dstool-Linux-x86_64 
tools/3dstool-Linux-x86_64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=a22fde25b5c664cf408bfcac4a5d255293a376ba, not stripped

 Universal-Inject-Generator git:(master) file tools/MergeExHeader-Linux-x86_64 
tools/MergeExHeader-Linux-x86_64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=bf5f844aa8b869ebaf25ffddffd9c3298634e8ec, not stripped
```

We still need ctrtool-Linux-i686.

**Comment by mariogamer2** [comment]
Build correctly,will try injecting...

P.S. ow do you get this file info?

**Comment by mariogamer2** [comment]
FBI work fine.

**Comment by lhallam** [comment]
I've built ctrtool for i686 (https://github.com/xalri/Universal-Inject-Generator)
I'll set up a VM to test it now.

edit: I didn't have the correct fork for ctrtool, trying again now..
edit2: It works now ^^

Just to be sure: https://github.com/profi200/Project_CTR is the correct repo?

**Comment by lhallam** [comment]
The file information is from the `file` command (http://linux.about.com/library/cmd/blcmdl1_file.htm)

**Comment by mariogamer2** [comment]
If it work,create a pull to my branch.

**Comment by mariogamer2** [comment]
Yes it is. (profi200 fork)

**Comment by d0k3** [comment]
Alright, as I see, this is tested, taking this over now.

**Pull request merged**
