### PR TITLE
Add OS X support and clean output

### PR DESCRIPTION
**Pull request by swarzesherz**

### CODE REVIEW

**Comment by d0k3** [comment]
Thanks a ton for this! This looks like it needs AWK, though - is this reliably available on both platforms, or would the user have to get it from somewhere else?

**Comment by swarzesherz** [comment]
Replaced by cut available in both platformos

**Comment by d0k3** [comment]
Thanks, merged!

**Comment by swarzesherz** [comment]
In last time changed again to awk available in most popular distributions of linux and functionality is same in OSX

**Comment by d0k3** [comment]
I was too fast?  You can send me another one, though.

**Comment by swarzesherz** [comment]
It's no necessary when you merged this PR, already made the change and all is OK, sorry for inconvenience

**Pull request merged**
