### PR TITLE
~Patched the script to allow spaces in all filenames involved.

### PR DESCRIPTION
**Pull request by IcySon55**
I didn't patch the Linux shell scripts. Maybe somebody else can port this fix over to those.

### CODE REVIEW

**Comment by d0k3** [comment]
Sorry, missed that. I trust this is properly tested?

**Comment by IcySon55** [comment]
Indeed. Used it to inject FBI for three systems. I also posted my changes in the thread on temp but only got around to creating the pull request now.

**Comment by d0k3** [comment]
Trusting you on that, merged

**Comment by IcySon55** [comment]
I found the post: http://gbatemp.net/threads/release-inject-any-app-into-health-safety-o3ds-n3ds-cfw-only.402236/page-4#post-5842946

In any case, I tested the script several times before using it to create the injects on the systems. Making sure that the output files weren't all the same which was happening before. Include 2 or more CIA files and all the output files would be the same size and have the same hash as the first file.

**Pull request merged**
