### PR TITLE
Use prebuilt dummy.bin

### PR DESCRIPTION
**Pull request by pixel-stuck**

### CODE REVIEW

**Comment by d0k3** [comment]
Can you squash these commits? Everything from 0fbe020 up to and including c98ef2a can easily be squashed into one. If you don't know how to squash, in git shell:
- git rebase -i head~6
- Edit the text file (change 'pick' to 's' only for those commits that should be squashed into the previous one), then close
- Edit the next text file (new commit message), then close
- If everything went well: git push --force

**Comment by pixel-stuck** [comment]
Sure I'll do that, sorry about the mess

**Comment by d0k3** [comment]
No problem at all :). I'm trying to keep the commit history clean. If you need help, just let me know. And shoot me another message once you're finished.

**Comment by pixel-stuck** [comment]
Sorry it's taking awhile I've been sick the past few days so I haven't done much more than sit on my phone, eat, sleep etc. I'm finally feeling better so I should have it up tomorrow

**Comment by pixel-stuck** [comment]
alright there we go, they're all merged into one

**Comment by d0k3** [comment]
Oh well, now something seems to be seriously wrong (just take a look at the commit history). No problem, I'll see about fixing this, but you might have to fork anew afterwards. I'll let you know once I've got this. Hope you are already better now!

**Comment by d0k3** [comment]
... and now it looks better, but it also looks like I did the fix for the dummy.bin in Linux instead of you. Sorry! If you think that's okay, you may just delete your fork and fork again. Otherwise, we can try to revert the last commit and redo it, so your participation is properly credited.

**Comment by pixel-stuck** [comment]
Meh, I don't really care as long as it's in there

**Pull request merged**
